### ISSUE TITLE
データベース設計-倉持

### ISSUE THREAD

**Issue by isenaz** [isenaz/cdle_youth_handson_app_1#4]
# タスク概要
[要件](https://docs.google.com/document/d/1JvS1REVHzhjGBDe5bCvjBXn34bahyP3d5qDN_LXX_HQ/edit#heading=h.eyrp6vjxfe84)を満たす上で必要なデータを定義して、ER図を完成させる。

# 補足
* テーブル定義では「テーブル定義書」と「ER図」の２つを作ることが多いですが、全部やると大変だと思うので今回作るのはひとまずER図だけにします。余裕があったらテーブル定義書も作ってOKです。
* ER図はdrawioというツールで作れて、グーグルドライブ上で編集・閲覧できます。他に使いたいツールがあったらそれでもOKです。
* 途中で困ったりしたら適宜相談してください
* 序盤で方向性が異なっていると修正が困難なので、キリの良い所まで進む度に共有をすると仕事が進みやすいです

**Comment by Mochi-Moch1** [comment]
簡単にですが、テーブルを作成しました。
進捗過程として、共有します。確認よろしくお願いします。
![スクリーンショット 2022-09-29 16 55 35](https://user-images.githubusercontent.com/71626403/192973731-741ef195-8973-4715-a109-399caf3d4e23.png)

**Comment by Mochi-Moch1** [comment]
物理名に変換し、型をつけました。
![スクリーンショット 2022-09-29 17 13 22](https://user-images.githubusercontent.com/71626403/192977593-bd428a8f-f06e-4878-89fe-42d017d23e49.png)

**Comment by Mochi-Moch1** [comment]
リレーションを加えました。
一通りの設計を終えました。
![スクリーンショット 2022-09-29 17 38 35](https://user-images.githubusercontent.com/71626403/192983352-52fd81a6-efff-4a84-ade8-e9e5c86d16e0.png)

**Comment by Mochi-Moch1** [comment]
共有リンクです。コメント可能にしてあります。
https://drive.google.com/file/d/1jR3p6RdJhohrVX-g9UDeYOnz7H0qHUKa/view?usp=sharing

**Comment by Mochi-Moch1** [comment]
編集可能な共有リンクです。
https://drive.google.com/file/d/1jR3p6RdJhohrVX-g9UDeYOnz7H0qHUKa/view?usp=sharing
