### ISSUE TITLE
データベース設計-蜂須賀

### ISSUE THREAD

**Issue by isenaz** [isenaz/cdle_youth_handson_app_1#5]
# タスク概要
[要件](https://docs.google.com/document/d/1JvS1REVHzhjGBDe5bCvjBXn34bahyP3d5qDN_LXX_HQ/edit#heading=h.eyrp6vjxfe84)を満たす上で必要なデータを定義して、ER図を完成させる。

# 補足
* テーブル定義では「テーブル定義書」と「ER図」の２つを作ることが多いですが、全部やると大変だと思うので今回作るのはひとまずER図だけにします。余裕があったらテーブル定義書も作ってOKです。
* ER図はdrawioというツールで作れて、グーグルドライブ上で編集・閲覧できます。他に使いたいツールがあったらそれでもOKです。
* 途中で困ったりしたら適宜相談してください
* 序盤で方向性が異なっていると修正が困難なので、キリの良い所まで進む度に共有をすると仕事が進みやすいです

**Comment by koroku1023** [comment]
![image](https://user-images.githubusercontent.com/81435054/193165266-3fef9123-7bef-4e74-89b5-9baa3c01f407.png)

@isasenth 
遅くなりました！ご確認お願いします。
画像関係のチャットボットもありましたが、ユーザーの入力した画像はDBには保存しない形で一旦作りました。アプリを閉じて、再びチャットボットを開いて元の画面を再表示する際に、DBと連携が必要なのかが現状ではわからなかったので、今日確認したいと思います。
機械学習モデルの学習に使った画像やテキストなどはDBに上げないでいいと考えています。gitにもあげなくてもいいのかな（特に画像はデータが大きいので）と思いました。機械学習モデルはフォルダにまとめて格納しておけば良いかなと思います。
