### ISSUE TITLE
環境構築-倉持

### ISSUE THREAD

**Issue by isenaz** [isenaz/cdle_youth_handson_app_1#7]
# タスク概要
Djangoの開発環境をDocker上で作成する

# 進め方
* developブランチから、 `feature/7-環境構築-蜂須賀` というブランチを切って進める
* 完成したらdevelopブランチにプルリクエストを送って、レビュアーに井坂（ @isasenth ）を登録する。

# 補足
* Docker上でDjangoが起動できて、初期状態でもOKなのでウェブサイトにアクセスできることが確認できたらOKです
* 途中で困ったりしたら適宜相談してください
* 序盤で方向性が異なっていると修正が困難なので、キリの良い所まで進む度に共有をすると仕事が進みやすいです

**Comment by Mochi-Moch1** [comment]
プルリクエストを送りました。ご確認よろしくお願いします。
